### 행정동/연령별 생활인구

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path='/content/drive/MyDrive/asac/project/eda/행정동 단위 서울 생활인구.csv'
original=pd.read_csv(path,encoding='cp949')
original

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20240416,0,11110515,14899.5056,535.6120,341.2932,566.9008,367.8391,393.6565,366.1924,...,433.2889,547.4291,641.7839,692.0008,789.2746,655.1199,623.8117,494.5813,358.3647,1064.2362
1,20240416,0,11110530,11950.8409,242.1455,107.6203,208.6825,227.5238,377.5778,433.3402,...,387.7491,476.6484,738.7801,558.7952,646.6245,538.7513,462.2064,386.4506,279.7263,852.5646
2,20240416,0,11110540,3810.7422,63.4048,48.5830,342.5010,315.9819,88.8251,109.7640,...,116.8609,133.0059,134.0762,169.6283,173.6922,136.7404,117.9504,126.0611,112.0652,294.3959
3,20240416,0,11110550,13168.9210,464.5441,360.2008,407.6991,436.8543,337.0918,321.1804,...,362.3948,390.8195,514.1649,568.7402,683.0929,537.7708,516.4312,475.5392,358.6432,970.6778
4,20240416,0,11110560,19068.0547,573.5476,414.8658,588.8726,561.2192,422.4865,371.3625,...,451.0720,446.7918,699.7527,746.9035,851.4926,889.0775,1053.6289,882.6779,648.1517,1658.0348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10171,20240416,23,11740650,26031.3529,1057.5576,366.8535,508.2558,557.8121,1018.5737,1106.8284,...,1330.1791,1177.1394,1104.1785,905.2416,1001.1110,956.2074,1070.8571,1034.4000,780.0014,1872.3708
10172,20240416,23,11740660,26702.5690,728.6321,437.9796,770.3003,839.2475,893.6291,1020.1256,...,1178.6519,1063.4490,1187.0322,1068.8885,1153.7546,966.5673,1251.6350,1065.6250,735.7319,1927.0843
10173,20240416,23,11740685,60083.8948,1729.8862,836.5140,1053.3184,1395.2873,2191.6890,2242.0348,...,2739.9213,2361.2775,2672.3236,2289.1663,2419.4643,2499.4059,2658.8166,2301.0791,1931.9553,4808.9864
10174,20240416,23,11740690,4595.2380,226.8373,171.9192,332.6917,99.9544,116.9440,94.3812,...,120.8600,103.9475,153.2904,158.7968,236.8808,162.2818,157.4005,154.0853,125.9054,344.4220
10175,20240416,23,11740700,26159.1571,1355.8470,683.9626,768.2323,613.2364,791.0925,867.3852,...,848.8464,849.6416,1042.4702,1007.9354,1104.6838,973.4658,1119.6975,947.7389,757.3620,1950.2465

시간대 09~16시로 필터링

In [ ]:
df=original
df=df[(df["시간대구분"]>=9)&(df["시간대구분"]<=16)]
df=df.reset_index()
df

,index,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,3816,20240416,9,11110515,20450.6233,1003.1267,639.1948,1256.1496,465.0636,513.1780,...,672.2816,627.2158,811.7398,791.0279,827.7932,680.2654,704.0924,572.8604,348.8782,1042.7323
1,3817,20240416,9,11110530,39578.9644,281.7992,125.2439,216.4985,564.9384,1459.1628,...,2702.4619,2481.6506,2926.7443,2278.1685,2225.0917,1531.5422,1224.4234,912.0816,664.9445,1182.6070
2,3818,20240416,9,11110540,7826.0900,96.0781,73.6186,372.1244,396.1161,284.3830,...,355.3649,347.7625,347.1617,374.4680,371.0287,260.8490,237.2386,178.9414,132.6401,349.7844
3,3819,20240416,9,11110550,13959.0825,239.8776,185.9976,440.4815,849.0279,383.8371,...,381.0104,352.1339,458.9151,488.2880,581.4119,449.9820,442.7554,437.7907,317.6806,870.7567
4,3820,20240416,9,11110560,16749.0245,252.4912,182.6351,487.9991,646.1306,403.8713,...,387.3821,361.1595,550.1421,643.0628,646.7445,818.6640,848.6072,783.6946,582.6099,1698.9535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,7203,20240416,16,11740650,20527.6524,848.0720,294.1852,277.2933,441.4729,650.7066,...,775.4923,756.6358,912.4764,808.6566,835.8692,846.3754,944.1587,917.7536,697.0596,1844.9145
3388,7204,20240416,16,11740660,25176.4739,778.8293,468.1537,998.6830,692.5718,752.5859,...,773.9953,805.8098,999.7675,1052.9327,1239.9382,1060.8614,1267.3144,967.9759,701.4524,1858.8161
3389,7205,20240416,16,11740685,51900.0621,1843.9635,891.6783,885.5866,1028.5113,1458.4479,...,1700.0253,1684.1877,2035.1358,1989.9903,2465.0325,2404.7094,2730.2281,2386.7390,1924.2497,4783.0375
3390,7206,20240416,16,11740690,4222.5664,181.5731,137.6135,436.8941,89.0179,107.5812,...,64.1282,86.7226,121.8129,128.7192,186.5058,131.2646,155.8955,144.3322,123.9572,239.8449
3391,7207,20240416,16,11740700,24356.5596,1313.0763,662.3869,639.5733,515.1508,662.1290,...,696.2070,845.0356,958.0499,885.5419,1041.3485,996.0488,1078.6824,964.8506,754.4952,2178.7000

In [ ]:
#기준일 하루로 추출
df=df[df["기준일ID"]==20240416]
df

,index,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,3816,20240416,9,11110515,20450.6233,1003.1267,639.1948,1256.1496,465.0636,513.1780,...,672.2816,627.2158,811.7398,791.0279,827.7932,680.2654,704.0924,572.8604,348.8782,1042.7323
1,3817,20240416,9,11110530,39578.9644,281.7992,125.2439,216.4985,564.9384,1459.1628,...,2702.4619,2481.6506,2926.7443,2278.1685,2225.0917,1531.5422,1224.4234,912.0816,664.9445,1182.6070
2,3818,20240416,9,11110540,7826.0900,96.0781,73.6186,372.1244,396.1161,284.3830,...,355.3649,347.7625,347.1617,374.4680,371.0287,260.8490,237.2386,178.9414,132.6401,349.7844
3,3819,20240416,9,11110550,13959.0825,239.8776,185.9976,440.4815,849.0279,383.8371,...,381.0104,352.1339,458.9151,488.2880,581.4119,449.9820,442.7554,437.7907,317.6806,870.7567
4,3820,20240416,9,11110560,16749.0245,252.4912,182.6351,487.9991,646.1306,403.8713,...,387.3821,361.1595,550.1421,643.0628,646.7445,818.6640,848.6072,783.6946,582.6099,1698.9535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,7203,20240416,16,11740650,20527.6524,848.0720,294.1852,277.2933,441.4729,650.7066,...,775.4923,756.6358,912.4764,808.6566,835.8692,846.3754,944.1587,917.7536,697.0596,1844.9145
3388,7204,20240416,16,11740660,25176.4739,778.8293,468.1537,998.6830,692.5718,752.5859,...,773.9953,805.8098,999.7675,1052.9327,1239.9382,1060.8614,1267.3144,967.9759,701.4524,1858.8161
3389,7205,20240416,16,11740685,51900.0621,1843.9635,891.6783,885.5866,1028.5113,1458.4479,...,1700.0253,1684.1877,2035.1358,1989.9903,2465.0325,2404.7094,2730.2281,2386.7390,1924.2497,4783.0375
3390,7206,20240416,16,11740690,4222.5664,181.5731,137.6135,436.8941,89.0179,107.5812,...,64.1282,86.7226,121.8129,128.7192,186.5058,131.2646,155.8955,144.3322,123.9572,239.8449
3391,7207,20240416,16,11740700,24356.5596,1313.0763,662.3869,639.5733,515.1508,662.1290,...,696.2070,845.0356,958.0499,885.5419,1041.3485,996.0488,1078.6824,964.8506,754.4952,2178.7000

필요 없는 컬럼들 삭제

In [ ]:
df=df.drop("index",axis=1)
df

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20240416,9,11110515,20450.6233,1003.1267,639.1948,1256.1496,465.0636,513.1780,579.5006,...,672.2816,627.2158,811.7398,791.0279,827.7932,680.2654,704.0924,572.8604,348.8782,1042.7323
1,20240416,9,11110530,39578.9644,281.7992,125.2439,216.4985,564.9384,1459.1628,1874.1607,...,2702.4619,2481.6506,2926.7443,2278.1685,2225.0917,1531.5422,1224.4234,912.0816,664.9445,1182.6070
2,20240416,9,11110540,7826.0900,96.0781,73.6186,372.1244,396.1161,284.3830,321.4896,...,355.3649,347.7625,347.1617,374.4680,371.0287,260.8490,237.2386,178.9414,132.6401,349.7844
3,20240416,9,11110550,13959.0825,239.8776,185.9976,440.4815,849.0279,383.8371,283.5235,...,381.0104,352.1339,458.9151,488.2880,581.4119,449.9820,442.7554,437.7907,317.6806,870.7567
4,20240416,9,11110560,16749.0245,252.4912,182.6351,487.9991,646.1306,403.8713,363.4482,...,387.3821,361.1595,550.1421,643.0628,646.7445,818.6640,848.6072,783.6946,582.6099,1698.9535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,20240416,16,11740650,20527.6524,848.0720,294.1852,277.2933,441.4729,650.7066,766.7198,...,775.4923,756.6358,912.4764,808.6566,835.8692,846.3754,944.1587,917.7536,697.0596,1844.9145
3388,20240416,16,11740660,25176.4739,778.8293,468.1537,998.6830,692.5718,752.5859,808.6968,...,773.9953,805.8098,999.7675,1052.9327,1239.9382,1060.8614,1267.3144,967.9759,701.4524,1858.8161
3389,20240416,16,11740685,51900.0621,1843.9635,891.6783,885.5866,1028.5113,1458.4479,1573.2342,...,1700.0253,1684.1877,2035.1358,1989.9903,2465.0325,2404.7094,2730.2281,2386.7390,1924.2497,4783.0375
3390,20240416,16,11740690,4222.5664,181.5731,137.6135,436.8941,89.0179,107.5812,123.0729,...,64.1282,86.7226,121.8129,128.7192,186.5058,131.2646,155.8955,144.3322,123.9572,239.8449
3391,20240416,16,11740700,24356.5596,1313.0763,662.3869,639.5733,515.1508,662.1290,626.8296,...,696.2070,845.0356,958.0499,885.5419,1041.3485,996.0488,1078.6824,964.8506,754.4952,2178.7000

In [ ]:
col_size=len(df.columns)
col_size

32

In [ ]:
temp_df=df
len(temp_df.columns)

32

In [ ]:
age_band=10
#10대가 두개로 나뉜건 20~60대, 70대는 하나로
gap=14
#남자: 5 , 여자: 19부터 시작
for i in range(5,18,2):
  #70대인 경우
  if i==17:
    temp_df[str(age_band)+"대"]=temp_df.iloc[:,i]+temp_df.iloc[:,i+gap]

  else:
    temp_df[str(age_band)+"대"]=temp_df.iloc[:,i]+temp_df.iloc[:,i+1]+temp_df.iloc[:,i+gap]+temp_df.iloc[:,i+1+gap]

  age_band+=10



temp_df

5
7
9
11
13
15
17

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,10대,20대,30대,40대,50대,60대,70대
0,20240416,9,11110515,20450.6233,1003.1267,639.1948,1256.1496,465.0636,513.1780,579.5006,...,572.8604,348.8782,1042.7323,4088.6311,2550.9514,2726.8692,3007.9435,2635.2743,1628.7694,1650.1805
1,20240416,9,11110530,39578.9644,281.7992,125.2439,216.4985,564.9384,1459.1628,1874.1607,...,912.0816,664.9445,1182.6070,1327.3417,6115.0191,9887.6892,9566.9422,6801.1335,3060.3778,2109.1320
2,20240416,9,11110540,7826.0900,96.0781,73.6186,372.1244,396.1161,284.3830,321.4896,...,178.9414,132.6401,349.7844,904.1036,1233.3007,1405.1346,1639.8734,1184.8343,597.2316,571.2178
3,20240416,9,11110550,13959.0825,239.8776,185.9976,440.4815,849.0279,383.8371,283.5235,...,437.7907,317.6806,870.7567,2522.4022,2544.4984,1523.0589,1893.5932,1765.5834,1376.2420,1387.8010
4,20240416,9,11110560,16749.0245,252.4912,182.6351,487.9991,646.1306,403.8713,363.4482,...,783.6946,582.6099,1698.9535,2048.0630,2007.6515,1718.8242,2406.4754,2873.5734,2319.0555,2577.6358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,20240416,16,11740650,20527.6524,848.0720,294.1852,277.2933,441.4729,650.7066,766.7198,...,917.7536,697.0596,1844.9145,1130.9646,2424.0316,3340.3825,3259.1366,3313.8405,2783.3297,2915.5032
3388,20240416,16,11740660,25176.4739,778.8293,468.1537,998.6830,692.5718,752.5859,808.6968,...,967.9759,701.4524,1858.8161,2424.8877,2853.8776,3586.9496,4459.6154,4258.2464,3148.6257,2963.0716
3389,20240416,16,11740685,51900.0621,1843.9635,891.6783,885.5866,1028.5113,1458.4479,1573.2342,...,2386.7390,1924.2497,4783.0375,3364.1576,5359.4432,7196.2762,8294.9032,8823.2014,7282.5037,7788.3376
3390,20240416,16,11740690,4222.5664,181.5731,137.6135,436.8941,89.0179,107.5812,123.0729,...,144.3322,123.9572,239.8449,781.3773,296.2825,463.8998,647.8562,732.7582,525.6051,420.6358
3391,20240416,16,11740700,24356.5596,1313.0763,662.3869,639.5733,515.1508,662.1290,626.8296,...,964.8506,754.4952,2178.7000,2175.0928,2422.8765,3514.5975,3727.1167,3699.2615,2982.4349,3736.2652

In [ ]:
#필요 없는 앞쪽 인덱스 삭제
re=temp_df.drop(temp_df.columns[4:col_size],axis=1)
re

,기준일ID,시간대구분,행정동코드,총생활인구수,10대,20대,30대,40대,50대,60대,70대
0,20240416,9,11110515,20450.6233,4088.6311,2550.9514,2726.8692,3007.9435,2635.2743,1628.7694,1650.1805
1,20240416,9,11110530,39578.9644,1327.3417,6115.0191,9887.6892,9566.9422,6801.1335,3060.3778,2109.1320
2,20240416,9,11110540,7826.0900,904.1036,1233.3007,1405.1346,1639.8734,1184.8343,597.2316,571.2178
3,20240416,9,11110550,13959.0825,2522.4022,2544.4984,1523.0589,1893.5932,1765.5834,1376.2420,1387.8010
4,20240416,9,11110560,16749.0245,2048.0630,2007.6515,1718.8242,2406.4754,2873.5734,2319.0555,2577.6358
...,...,...,...,...,...,...,...,...,...,...,...
3387,20240416,16,11740650,20527.6524,1130.9646,2424.0316,3340.3825,3259.1366,3313.8405,2783.3297,2915.5032
3388,20240416,16,11740660,25176.4739,2424.8877,2853.8776,3586.9496,4459.6154,4258.2464,3148.6257,2963.0716
3389,20240416,16,11740685,51900.0621,3364.1576,5359.4432,7196.2762,8294.9032,8823.2014,7282.5037,7788.3376
3390,20240416,16,11740690,4222.5664,781.3773,296.2825,463.8998,647.8562,732.7582,525.6051,420.6358
3391,20240416,16,11740700,24356.5596,2175.0928,2422.8765,3514.5975,3727.1167,3699.2615,2982.4349,3736.2652

full_data로 이어붙이기

In [ ]:
income_path="/content/drive/MyDrive/asac/project/eda/filtered/income_gu.csv"
income_pd=pd.read_csv(income_path)
income_pd

,시군구명,행정동명,행정동코드,20대평균소득,30대평균소득,40대평균소득,50대평균소득,60대평균소득,70대이상평균소득,월평균소득
0,강남구,개포1동,11680660,0.00,454.600000,726.800000,1350.100000,1991.600000,403.100000,5.156498e+06
1,강남구,개포2동,11680670,NaN,NaN,NaN,NaN,NaN,NaN,5.147849e+06
2,강남구,개포4동,11680690,NaN,NaN,NaN,NaN,NaN,NaN,3.576102e+06
3,강남구,논현1동,11680521,88.25,494.275000,920.175000,1815.625000,787.850000,379.950000,3.313736e+06
4,강남구,논현2동,11680531,139.70,860.900000,929.450000,660.450000,403.100000,261.900000,4.003463e+06
...,...,...,...,...,...,...,...,...,...,...
418,중랑구,상봉2동,11260590,0.00,589.266667,810.233333,686.466667,468.533333,322.066667,2.590471e+06
419,중랑구,신내1동,11260680,290.40,628.200000,625.100000,556.200000,673.900000,474.833333,2.798343e+06
420,중랑구,신내2동,11260690,NaN,NaN,NaN,NaN,NaN,NaN,3.092304e+06
421,중랑구,중화1동,11260600,328.90,777.100000,1324.200000,681.000000,349.200000,360.300000,2.540502e+06
422,중랑구,중화2동,11260610,269.30,348.500000,448.000000,621.800000,923.100000,239.300000,2.265661e+06

In [ ]:
full_pd=pd.merge(income_pd,avg,
                 how="outer",
                 left_on="행정동코드",
                 right_on="행정동코드"
                 )

In [ ]:
seoul_code=pd.read_csv("/content/drive/MyDrive/asac/project/eda/filtered/seoul_code.csv")

In [ ]:
seoul_code

     Unnamed: 0     행정동코드    시도명 시군구명   읍면동명
0             0  11000000  서울특별시  NaN    NaN
1             1  11110000  서울특별시  종로구    NaN
2             2  11110515  서울특별시  종로구  청운효자동
3             3  11110530  서울특별시  종로구    사직동
4             4  11110540  서울특별시  종로구    삼청동
..          ...       ...    ...  ...    ...
447         447  11740650  서울특별시  강동구  성내제2동
448         448  11740660  서울특별시  강동구  성내제3동
449         449  11740685  서울특별시  강동구     길동
450         450  11740690  서울특별시  강동구  둔촌제1동
451         451  11740700  서울특별시  강동구  둔촌제2동

[452 rows x 5 columns]

In [ ]:
tt=pd.merge(seoul_code,original,
            how="inner",
            left_on="행정동코드",
            right_on="행정동코드")
tt["읍면동명"].nunique()

415

In [ ]:
merged=pd.merge(seoul_code,re,
                how="right",
                left_on="행정동코드",
                right_on="행정동코드")
merged

,Unnamed: 0,행정동코드,시도명,시군구명,읍면동명,기준일ID,시간대구분,총생활인구수,10대,20대,30대,40대,50대,60대,70대
0,2.0,11110515,서울특별시,종로구,청운효자동,20240416,9,20450.6233,4088.6311,2550.9514,2726.8692,3007.9435,2635.2743,1628.7694,1650.1805
1,3.0,11110530,서울특별시,종로구,사직동,20240416,9,39578.9644,1327.3417,6115.0191,9887.6892,9566.9422,6801.1335,3060.3778,2109.1320
2,4.0,11110540,서울특별시,종로구,삼청동,20240416,9,7826.0900,904.1036,1233.3007,1405.1346,1639.8734,1184.8343,597.2316,571.2178
3,5.0,11110550,서울특별시,종로구,부암동,20240416,9,13959.0825,2522.4022,2544.4984,1523.0589,1893.5932,1765.5834,1376.2420,1387.8010
4,6.0,11110560,서울특별시,종로구,평창동,20240416,9,16749.0245,2048.0630,2007.6515,1718.8242,2406.4754,2873.5734,2319.0555,2577.6358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,447.0,11740650,서울특별시,강동구,성내제2동,20240416,16,20527.6524,1130.9646,2424.0316,3340.3825,3259.1366,3313.8405,2783.3297,2915.5032
3388,448.0,11740660,서울특별시,강동구,성내제3동,20240416,16,25176.4739,2424.8877,2853.8776,3586.9496,4459.6154,4258.2464,3148.6257,2963.0716
3389,449.0,11740685,서울특별시,강동구,길동,20240416,16,51900.0621,3364.1576,5359.4432,7196.2762,8294.9032,8823.2014,7282.5037,7788.3376
3390,450.0,11740690,서울특별시,강동구,둔촌제1동,20240416,16,4222.5664,781.3773,296.2825,463.8998,647.8562,732.7582,525.6051,420.6358
3391,451.0,11740700,서울특별시,강동구,둔촌제2동,20240416,16,24356.5596,2175.0928,2422.8765,3514.5975,3727.1167,3699.2615,2982.4349,3736.2652

In [ ]:
cols=["10대","20대","30대","40대","50대","60대","70대"]
avg=merged.groupby(by=["시군구명","행정동코드","읍면동명"])[cols].mean()
avg

                             10대           20대           30대           40대  \
시군구명 행정동코드    읍면동명
강남구  11680510 신사동    3331.706688   9434.136437  11340.085213   9854.956238
     11680521 논현1동   1047.267175  13027.133175  16636.803825  12442.709263
     11680531 논현2동   2075.827375  14636.427487  20259.997812  16204.390537
     11680545 압구정동   3357.125588   9525.193400  12524.620812  11282.991762
     11680565 청담동    2788.697200  10237.924387  14275.686000  12005.497487
...                          ...           ...           ...           ...
중랑구  11260630 묵제2동    653.815788   1859.681800   2113.635363   2419.399063
     11260655 망우본동   5159.326662   3982.796550   5223.537650   5657.378862
     11260660 망우제3동   942.914487    787.338500    924.224050   1202.622412
     11260680 신내1동   2175.724837   3084.010175   4161.674225   5016.693012
     11260690 신내2동   1143.125675   1343.050313   1931.674625   2252.526600

                             50대          60대          70대
시군구명 행정동코드    읍면동명
강남구  11680510 신사동    6339.548963  3800.585700  3572.862225
     11680521 논현1동   6801.520850  3439.393088  2944.610113
     11680531 논현2동   8752.512150  4238.482925  3484.727300
     11680545 압구정동   6903.069650  4136.663738  4047.287350
     11680565 청담동    7771.168825  4562.992125  3210.817013
...                          ...          ...          ...
중랑구  11260630 묵제2동   2615.254000  2212.712550  2278.019250
     11260655 망우본동   5808.421950  4909.105825  4597.663588
     11260660 망우제3동  1385.297575  1219.379463  1302.113775
     11260680 신내1동   4922.691975  3780.614687  3803.668363
     11260690 신내2동   2345.476463  1879.873325  2115.394288

[416 rows x 7 columns]

In [ ]:
len(avg)

416

In [ ]:
avg.to_csv("/content/drive/MyDrive/asac/project/eda/filtered/time_people.csv",encode="utf-8")
avg.to_excel("/content/drive/MyDrive/asac/project/eda/filtered/time_people.xlsx")

In [ ]:
avg.to_csv("/content/drive/MyDrive/asac/project/eda/filtered/time_people.csv",encoding="utf-8")